In [1]:
import numpy as np

In [2]:
np.nan ## asi se verian en numpy

nan

In [3]:
array = np.array([1,2,np.nan, 4,5])
array

array([ 1.,  2., nan,  4.,  5.])

In [4]:
##ver valores no validos en un array
np.isnan(array)

array([False, False,  True, False, False])

In [5]:
## manejar no vlaidos en calculos
##Promedio
np.mean(array)

np.float64(nan)

In [6]:
##sale nan por el no valido

In [7]:
np.nanmean(array) ##considera los nan y los ignora

np.float64(3.0)

In [8]:
##sustitución de nan
array_con_cero = np.where(np.isnan(array), 0, array) ##mira si hay nan en array, si hay cambia por cero, sino deja igual
array_con_cero

array([1., 2., 0., 4., 5.])

In [9]:
promedio = np.nanmean(array)
array_con_promedio = np.where(np.isnan(array), promedio, array)
array_con_promedio

array([1., 2., 3., 4., 5.])

In [14]:
##eliminar los nan
array_filtrado = array[~np.isnan(array)] ##el icon ~ hace lo contrario a la declaracion, osea is nan devolvia solo el nan, ahora con ~ develve todos menos el nan

In [15]:
array_filtrado

array([1., 2., 4., 5.])