In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
## Métodos
array.shape

(9,)

In [5]:
## 9 de largo pero lo demas vacio es una sola dimension

In [6]:
array_mod = array.reshape(3,3) ## bidimension de 3 columnas con 3 items cada uno
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
## Si le pones -1 
array_mod_2 = array.reshape(-1,3) ## con el -1 calcula solo resumidamente
array_mod_2 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
## voltear el array, columnas a filas y viceversa
array_volteado = array_mod_2.transpose()
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
## cambiaron las filas por columnas y viceversa

In [10]:
## Flatten
array_flat = array_mod.flatten()
array_flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
## flatten hizo una copia achatada del original, dejo de ser bidimensional

In [12]:
array_ravel = array_mod.ravel() ## igual que flat pero ravel crea una vista,no ocupa memoria por crear una copia como flat

In [13]:
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])