In [1]:
import numpy as np
array1d = np.array([1,2,3,4,5])
array2d = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [2]:
## 1er elemento del array 1d
array1d[0]

np.int64(1)

In [3]:
array1d[-1]

np.int64(5)

In [4]:
## en el 2d
array2d[0]

array([1, 2, 3])

In [5]:
array2d[0][1]

np.int64(2)

In [6]:
array1d[1:4]

array([2, 3, 4])

In [7]:
## en 2d
array2d[1,:] ## todo es :

array([4, 5, 6])

In [8]:
array2d[1,1:3] 

array([5, 6])

In [9]:
array2d[:, 1]

array([2, 5, 8])

In [10]:
array2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [11]:
##booleana
array1d > 3

array([False, False, False,  True,  True])

In [12]:
array2d  % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])